services:

  db:
    container_name: teste_guia_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./prisma/sql/:/docker-entrypoint-initdb.d/

  app:
    container_name: app_python
    build:
      context: .  
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db  
    volumes:
      - .:/app  
    command: python src/main.py 

volumes:
  postgres: